name: Sync addon docker images to Aliyun

on:
  push:
    paths:
      - '**.json'
    branches:
      - 'panther'
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - id: load_version
        run: |
          content=`cat ./stable.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=packageJson::$content"
          
      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: "${{ secrets.ALIYUN_REGISTRY_USERNAME }}"
          password: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"

      -
        name: Get tag mosquitto
        id: latest_tag_mosquitto
        uses: jacobtomlinson/gha-get-docker-hub-tags@0.1.3
        with:
          org: 'homeassistant'  # Docker Hub user or organisation name
          repo: 'aarch64-addon-mosquitto'
        
      -
        name: Pull and push mosquitto
        run: |
          mosquitto_version="${{ steps.latest_tag_mosquitto.outputs.tag }}"
          docker pull homeassistant/aarch64-addon-mosquitto:$mosquitto_version
          docker tag homeassistant/aarch64-addon-mosquitto:$mosquitto_version registry.cn-hangzhou.aliyuncs.com/panther-ha/aarch64-addon-mosquitto:$mosquitto_version
          docker push registry.cn-hangzhou.aliyuncs.com/panther-ha/aarch64-addon-mosquitto:$mosquitto_version
