name: Release docker images

on:
  push:
    paths:
      - '**.json'
    branches:
      - 'panther-ha'
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - id: load_version
        run: |
          content=`cat ./stable.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=packageJson::$content"

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: "${{ secrets.ALIYUN_REGISTRY_USERNAME }}"
          password: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./supervisor
          platforms: linux/arm64
          push: true
          build-args: |
            BUILD_FROM=ghcr.io/home-assistant/aarch64-hassio-supervisor:${{fromJson(steps.load_version.outputs.packageJson).supervisor}}
          tags: |
            ghcr.io/panther-ha/aarch64-hassio-supervisor:${{fromJson(steps.load_version.outputs.packageJson).supervisor}}
            registry.cn-hangzhou.aliyuncs.com/panther-ha/aarch64-hassio-supervisor:${{fromJson(steps.load_version.outputs.packageJson).supervisor}}
